on:
  push:
    branches:
      - master
  pull_request:

name: Run unit tests

jobs:
  test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC", 
            os: ubuntu-latest,
            cov: false
          }
        - {
            name: "macOS Latest Clang", 
            os: macos-latest
          }

    steps:
    - uses: actions/checkout@v3

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Configure the build for Mac
      if: ${{ matrix.config.os == 'macos-latest' }}
      run: cmake -S . -B build

    - name: Configure the build with coverage
      if: ${{ matrix.config.os == 'ubuntu-latest' }}
      run: cmake -S . -B build -DCODE_COVERAGE=ON 

    - name: Run the build
      run: cmake --build build

    - name: Run the tests
      run: |
        cd build
        ctest

    - name: Generate code coverage
      if: ${{ matrix.config.os == 'ubuntu-latest' }}
      run: |
        cd build/tests/CMakeFiles/
        find -type f -name "*.gcno" -execdir gcov -abcfu {} +

    - name: Upload to Codecov
      if: ${{ matrix.config.os == 'ubuntu-latest' }}
      uses: codecov/codecov-action@v3
      with:
        directory: build/tests/CMakeFiles/        
